---
hostname: prg-cor02
mlag:
  domain_id: 1000          # Must match prg-cor01
  peer_ip: 192.0.2.0       # prg-cor01's local_ip
  local_ip: 192.0.2.1/31   # /31 subnet
  heartbeat_interval: 2500 # 2.5s heartbeat
  reload_delay: 150        # 150s reload delay
interfaces:
  - name: Port-Channel1
    description: MLAG_PEER
    type: mlag_peer
  - name: Ethernet2
    description: SERVER01
    ip: 10.10.10.2/24
aaa:
  username: autocon
  password: autocon3
ntp_servers:
  - 203.0.113.1
  - 198.51.100.1
ospf:
  router_id: 1.1.1.2       # Unique loopback IP
  networks:
    - 192.0.2.0/31
    - 10.10.10.0/24
loopback:
  ip: 1.1.1.2/32

